# Generated by Django 3.1.2 on 2021-05-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='Time',
        ),
    ]
