# Generated by Django 3.1.2 on 2021-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_auto_20210514_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('Amount', models.IntegerField(max_length=200)),
            ],
        ),
    ]
