# Generated by Django 3.1.2 on 2021-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0003_donatedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedetail',
            name='Amount',
            field=models.IntegerField(max_length=20000),
        ),
    ]
