# Generated by Django 3.1.2 on 2021-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0005_auto_20210515_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
